ssdsept19-master/config/routes.rb
Rails.application.routes.draw do
  
  resources :items
  root 'static_pages#home'

  get '/help' => 'static_pages#help'

  get '/about' => 'static_pages#about'
  
  
  get '/login' => 'user#login'
  
    get '/logout' => 'user#logout'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

ssdsept19-master/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ssdsept19-master/app/models/item.rb
class Item < ApplicationRecord
end

ssdsept19-master/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

ssdsept19-master/app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :description, :price, :image_url, :category, :brand)
    end
end

ssdsept19-master/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

ssdsept19-master/app/controllers/user_controller.rb
class UserController < ApplicationController
    
    
    def login
        
    session[:login] = 1
    flash[:notice] = "User Just Logged In"
    redirect_to :controller => :items
    
    end

    
    def logout
        
      session[:login] = nil
    flash[:notice] = "Ok ... See You Next Time"  
redirect_to :controller => :items
  end     
    
    
    
    
end

ssdsept19-master/app/helpers/application_helper.rb
module ApplicationHelper
end

ssdsept19-master/app/helpers/items_helper.rb
module ItemsHelper
end

ssdsept19-master/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

ssdsept19-master/app/helpers/user_helper.rb
module UserHelper
end

ssdsept19-master/app/views/items/_form.html.erb
<%= form_for(item) do |f| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :image_url %>
    <%= f.text_field :image_url %>
  </div>

  <div class="field">
    <%= f.label :category %>
    <%= f.text_field :category %>
  </div>

  <div class="field">
    <%= f.label :brand %>
    <%= f.text_field :brand %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ssdsept19-master/app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

ssdsept19-master/app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

 <div id="itemsContainer">
  
  <h1>Items</h1>
     
      <% @items.each do |item| %>
      <div class="itemhols">
       <h1><%= item.title %></h1>
       
       <%= link_to (image_tag item.image_url, :class => "itemholsIm"), item %>
        <p><%= item.description %></p>
       <p>Price <%= number_to_currency(item.price, :unit => "€") %>
       <br>
        Category: <%= item.category %>
        <br>
        Brand: <%= item.brand %></p>
       
       <p>
         <%= link_to 'Show',  item, :class => "button", :role => "button" %>
         
         <% if session[:login] == 1 %>
         <%= link_to 'Edit',  edit_item_path(item), :class => "button", :role => "button" %>
         <%= link_to 'Destroy',  item, method: :delete, data: { confirm: 'Are you sure?' }, :class => "button", :role => "button" %>
         <% end %>
         
         
         
         <a href="/cart/<%= item.id %>" class="button">Add To Cart</a>
       </p>
        
      </div>
    <% end %>
      
</div>

<br>
<% if session[:login] == 1 %>    
<%= link_to 'New Item', new_item_path, :class =>"button", :role=>"button" %>
<% end %>

ssdsept19-master/app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

ssdsept19-master/app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @item.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @item.image_url %>
</p>

<p>
  <strong>Category:</strong>
  <%= @item.category %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @item.brand %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

ssdsept19-master/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GolfStore</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    
    
    <header class="headSec">
      <h1>Wednesday Night Golf Goodies!</h1>
      
      <ul>
        <li><%= link_to "HOME", "/" %></li>
        <li><%= link_to "PRODUCTS", "/items" %></li>
        <li><%= link_to "ABOUT", about_path %></li>
        <li><%= link_to "HELP", help_path %></li>
        <li><%= link_to "Log In", "/login" %></li>
        <li><%= link_to "Log Out", "/logout" %></li>
        
      </ul>
      
    </header>
    
    <div class="container">
      
      <%= yield %>
      
    </div>
    
    <footer class="footer">
      <h1>Look Im At The Bottom.....</h1>
      
    </footer>
  </body>
</html>

ssdsept19-master/app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

ssdsept19-master/app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

ssdsept19-master/app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>


<div class="mainCont">
    
    <h1>HOME</h1>

<p>Welcome this is the home page ..... more to come</p>    
</div>